# Generated by Django 3.2.7 on 2021-10-02 15:07

import creditcards.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_no', creditcards.models.CardNumberField(max_length=25)),
                ('cardhholder_name', models.CharField(max_length=50)),
                ('expiry_date', creditcards.models.CardExpiryField()),
                ('cvv', creditcards.models.SecurityCodeField(max_length=4)),
                ('balance', models.FloatField()),
            ],
        ),
    ]
