# Generated by Django 3.2.7 on 2021-10-08 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentsapi', '0004_alter_user_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='name',
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
